<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ClosedXML" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UMCMS.Domain\UMCMS.Domain.csproj" />
    <ProjectReference Include="..\UMCMS.Data\UMCMS.Data.csproj" />
  </ItemGroup>
</Project>
