<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UMCMS.Domain\UMCMS.Domain.csproj" />
  </ItemGroup>
</Project>
